php_versions:
  - major: "7"
    minor_versions:
      - minor: "7.2"
        base_os:
          - name: buster
            default: true
        patch_versions:
          - 7.2.34
  - major: "5"
    minor_versions:
      - minor: "5.6"
        base_os:
          - name: stretch
        patch_versions:
          - 5.6.40
php_variations:
  - name: cli
  - name: fpm
