php_versions:
  - major: "7"
    minor_versions:
      - minor: "7.2"
        base_os:
          - name: buster
            default: true
        patch_versions:
          - 7.2.34
php_variations:
  - name: cli
    default: true
  - name: fpm
  - name: fpm-apache
    supported_os: # Open a discussion on serversideup/php if you want to see Alpine support for fpm-apache (https://github.com/serversideup/docker-php/discussions/66)
      - buster